INSERT INTO Product ( REGULAR_PRICE,PROD_NAME, PROD_DESC) VALUES( 300,'ProductB3','pnavn3');
INSERT INTO Product ( REGULAR_PRICE,PROD_NAME, PROD_DESC) VALUES( 400,'ProductB4','pnavn4');
INSERT INTO Product ( REGULAR_PRICE,PROD_NAME, PROD_DESC) VALUES(500,'ProductB5','pnavn5');